### ISSUE TITLE
"riot-router" was already taken

### ISSUE THREAD

**Issue by cognitom** [riot/route#1]
As natural naming convention, `riot-router` seems the best. But this name was already taken by another user. (and that seems also a nice library)
https://www.npmjs.com/package/riot-router

At this time, I've chosen `riot-route` for the package name.
https://github.com/riot/router/blob/master/package.json#L2

Any thought?

**Comment by tipiirai** [comment]
I think we should contact the author and ask if he is willing to collaborate.

**Comment by cognitom** [comment]
@tipiirai it would be great ;)

**Comment by cognitom** [comment]
I'm waiting the answer from the author...
https://github.com/gabrielmoreira/riot-router/issues/6

Maybe summer vacation, go easy.

**Comment by Mouvedia** [comment]
https://docs.npmjs.com/cli/deprecate

**Comment by cognitom** [comment]
@Mouvedia we have no right to do that.
I'm starting thinking another name to just publish to npm.

- `riot-route`
- `riot-routing`
- `riot-way`

Is there any candidate?

**Comment by tipiirai** [comment]
I vote for `riot-route`. This repo needs to be renamed accordingly. 

@gabrielmoreira – can you please give us your voice! Thanks.

**Comment by cognitom** [comment]
OK, now we've published this repo as `riot-route`! :v:
https://www.npmjs.com/package/riot-route

@gabrielmoreira finally we decided to go with `riot-route` because it has more consistency to original Riot's naming convention and documentations. But your contribution to this repo will be always welcome. Thanks.

**Comment by gabrielmoreira** [comment]
@cognitom, @tipiirai 
Sorry... I was on vacation with family. I turned off the internet... 

I could release the name if necessary. I would just ask to put a footnote to the people who were already using. I'm using riot-router in production on my project.

**Comment by Mouvedia** [comment]
That's where deprecate comes into play.

**Comment by cognitom** [comment]
@gabrielmoreira No prob! Thank you for contacting us.
I know, guys should turn off the internet, when we stay with family :smile: 

I think you don't have to release it, but little confusable for users? @tipiirai Thoughts?
