### ISSUE TITLE
Mounting error with wildcard with route+tag

### ISSUE THREAD

**Issue by kiichi** [riot/route#101]
Hello,

I'm trying to use the Tag based router example with custom inner tag

```html
<router>
      <route path=""><p>Welcome Homepage</p></route>
      <route path="search"><search></search></route>
      <route path="history"><history></history></route>
      <route path="settings"><settings></settings></route>
</router>
```
but this code below generates error when the tag is looking for the [parent object](https://github.com/riot/route/blob/master/src/tags/route.tag#L7).

```javascript
riot.compile(function() {       
    riot.mount('*') // Uncaught TypeError: Cannot read property 'route' of null
})
```

- riot.js 3.6.1
- route+tag.js 3.1.1

http://plnkr.co/edit/Pz0EH8atDwUf59tCR8vR?p=preview

Is this wrong way to initialize tag based router? if this works, the code looks much cleaner... thank you!

**Comment by ufocool** [comment]
fix this problem:
1. Move <router>...</router> in *.tag, example main.tag
2. Enable main.tag in html, <script type="riot/tag" src="main.tag"></script>
3. Add tag <main></main> in <body> after <a href ..... >  on your html files

**Comment by GianlucaGuarini** [comment]
avoid the `*` and mount only your root tag http://plnkr.co/edit/UUvLw0jyjJupsnlFmL2Y?p=preview

**Comment by kiichi** [comment]
ah it make sense, it works with

```javascript
riot.mount('router') 
```

Thanks a lot

**Comment by bachly** [comment]
`riot.mount('route')` works
