### ISSUE TITLE
Error on route+tag: Cannot set property 'show'

### ISSUE THREAD

**Issue by ufocool** [riot/route#102]
Hello my friends. Please help me.

- riot.js 3.6.1
- route+tag.js 3.1.1

http://plnkr.co/edit/y0XQrs?p=preview

click menu1 -> click sub1 -> click menu2 -> click menu1 -> click sub1 -> error:

> Uncaught TypeError: Cannot set property 'show' of undefined

**Comment by GianlucaGuarini** [comment]
fixed with https://github.com/riot/route/pull/100

**Comment by GianlucaGuarini** [comment]
fixed in v3.1.2
