### ISSUE TITLE
Symbol '+' in route+tag.min.js and HTTP/2 protocol

### ISSUE THREAD

**Issue by ufocool** [riot/route#103]
Hello my friends. 
Im enable HTTP/2.0 protocol in my project and loading route+tag.min.js says:
` Status Code:404 `
If remove symbol ‘+’ in route+tag.min.js => route.tag.min.js result:
` Status Code:200`
Symbol ‘+’ not valid on names in h2 protocol? 
Yes all files are present in the directory 8-)

**Comment by GianlucaGuarini** [comment]
use `route%2Btag.min.js` instead
