### ISSUE TITLE
Using riot-route with webpack3

### ISSUE THREAD

**Issue by zorgoz** [riot/route#108]
Hello,

I am struggling for a while, and still can't find any solution how to properly import `riot-route` in my code.
If I use `import route from 'riot-route';` in my `vendor.js`, I am getting this output, while no riot-route code is actually added to my emitted vendor.js and 
```
var r = route.create()
```
is failing:
![image](https://user-images.githubusercontent.com/1569170/30275103-7bc059f8-9700-11e7-9b31-ccc6c9596fc3.png)
The only way I can see route code in my emitted vendor.js is using `import 'riot-route/dist/route+tag.min.js';`
But my code is still failing to compile:
![image](https://user-images.githubusercontent.com/1569170/30275187-cd200708-9700-11e7-9f1d-8db19913d793.png)
I have tried also to add route to `webpack.ProvidePlugin` as with jquery, but no effect.

Important note: I am using `riot-tag-loader`, which is working just fine as long I don't want to create a route object in my tag code.

**Comment by zorgoz** [comment]
I have a workaround, but not really nice:

1.  `import route from 'riot-route';`
2.  in webpack.config.js:
```
new webpack.ProvidePlugin({
        ...
        riot: 'riot',
        rr: 'riot-route',
        ....
    })
```
3.  in main.js (my entry point for webpack)
```
var g = window || global;
g.route = rr.default;
```

**Comment by pmcalabrese** [comment]
try to have a look here

https://pmcalabrese.github.io/riotjs-webpack/
