### ISSUE TITLE
Question: Is it possible with know the current route?

### ISSUE THREAD

**Issue by pmcalabrese** [riot/route#109]
I'd like to know my current route, there is a way with the router? or should I use regular JS?

**Comment by bminer** [comment]
I have the same issue.  How do you quickly query the current route?

**Comment by jrmykolyn** [comment]
Hey @pmcalabrese 

Do you need to transform/adjust the current route (ie. are you trying to extracting a value from it), or is your use cases similar to what @bminer described (ie. emphasize links which match the current route)?

**Comment by GianlucaGuarini** [comment]
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.
