### ISSUE TITLE
<route> tag with `title` attribute/option

### ISSUE THREAD

**Issue by bminer** [riot/route#111]
It would be cool if `riot-route/tag` could be extended so that `<route>` tags can attach `title` attributes to set the page title if the `path` of the `<route>` tag matches.

I can submit a PR if you are interested.  What do you think?

**Comment by GianlucaGuarini** [comment]
@bminer it sounds good go for it!

**Comment by GianlucaGuarini** [comment]
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.
