### ISSUE TITLE
Question: What is the difference between firstParser and secondParser

### ISSUE THREAD

**Issue by revington** [riot/route#112]
I read the documentation but I still don't get it

**Comment by jrmykolyn** [comment]
Hey @revington

I recently peaked under the hood of the Riot.js router, so I'm happy to take a crack at answering your question. However, there's one caveat: the info below assumes that that you're using the default `parser` and `secondParser` functions (ie. you haven't provided custom parsers via `route.parser( <custom-parser>, <custom-second-parser> )`).

Hope this helps!

CC: @GianlucaGuarini and @cognitom.

## TL DR
### `parser`
- Splits the path string (ie. `/products/1/edit`) into an array of path segments (ie. `[ 'products', '1', 'edit' ]`).
- Used in all cases if application does not inlude custom route filters.

### `secondParser`
- Only used if the application includes custom filters (ie. `route( 'products/*', ( id ) => { ... } )`).
- If a given route matches the custom filter, then the second parser applies the corresponding RegEx and returns any match groups.
- Based on the example above, the route 'products/1' would trigger the custom parser, which would extract and return '1'

## The Details
### `parser`
To provide a point of comparison, I'll start with a quick overview of the default `parser` function. This function is defined by the Riot.js router, and is used to split path strings into an array of path segments.

If an application DOES NOT provide any custom filters, then the default `parser` will be invoked on each route change, and the resulting 'path segment' array will be provided as arguments to the applications 'route change' callback. See the example below:

```
// Invocation below DOES NOT include a custom filter, so the default `parser` will be used on route change.
route( ( ...args ) => {
    // `args` will contain an array of path segments.
    // For example:
    // - Given the route 'products/', `args` will be equal to `[ 'products' ]`
    // - Given the route 'products/1/edit', `args` will be equal to `[ 'products', '1', 'edit' ]`
} );
```

### `secondParser`
The second parser is only used if the application includes at least 1x custom filter. In this case, the second parser serves two purposes:

    1. It converts 'wildcard' values to their corresponding regular expressions.
    2. It applies the resulting regular expression to the new path and returns the contents of any match groups.

This behavior is useful in cases where the application must respond to a very specific route, especially if it also needs to extract a specific segment.

```
// Invocation below includes a custom filter, meaning that the `secondParser` will be used to parse the corresponding route.
// This filter will match:
// - `products/1`,
// - `products/2`, etc.
// But not:
// - `products`
// - `products/1/edit`
route( 'products/*', ( id ) => {
    // Since the filter only includes 1x 'wildcard', the callback function will be invoked with 1x argument.
} );
```

**Comment by revington** [comment]
Hey @jrmykolyn thanks for such  a complete answer, definitely this should be included in the docs

**Comment by GianlucaGuarini** [comment]
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.
