### ISSUE TITLE
How to use parser with trails segments

### ISSUE THREAD

**Issue by stefanKBL** [riot/route#114]
Hi, having url like page/category_name/page_id
as i have multiple category and cannot use wildcard (page url in this case can be without other segment)
how to parse this kind of url and return category_name and page_id as variable to the route('page', function(category,id) {...})

Thanks

**Comment by AndersonBargas** [comment]
Hello @skobeo . There´s a special reason to avoid the wildcard at the route configuration?
Can you give a couple of real examples to clarify the problem?
Thanks in advance.

**Comment by GianlucaGuarini** [comment]
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.
