### ISSUE TITLE
Makes route.exec() callable without callback

### ISSUE THREAD

**Issue by cognitom** [riot/route#12]
@tipiirai can't we change the API of `route.exec()`?

v2.2 allowed a custom callback for this function, but I'd like to make it callable without a callback.

```javascript
// v2.2
riot.exec(callback)

// v2.3
riot.exec()
```

I often use it this manner in v2.2, but it looks redundant:

```javascript
// v2.2
var callback = function(id) {
  /* do something */
}
riot(callback)
riot.exec(callback)
```

And if there're multiple routings, we have no way to `exec`. Any advice or thought?
(At this time, this would be the only point which is not compatible with v2.2)

**Comment by tipiirai** [comment]
I didn't even know `exec` supports a callback so totally fine for me to drop.

**Comment by cognitom** [comment]
@tipiirai thanks for your feedback ;-)
I've added a deprecation warning to the docs:
https://github.com/riot/route/tree/dev/doc#routeexec
