### ISSUE TITLE
URL with both wildcards "*" and ".." fail parsing

### ISSUE THREAD

**Issue by guilhermetrovo** [riot/route#120]
An example of URL is:
`/search/advanced?test=123`

The configuration is:
`
route("/search/*..", function(type) {
        let params = route.query();
        let testParam = params.test;
        // type == "a"
        // testParam == 123
});
`

**Comment by guilhermetrovo** [comment]
I fixed it locally by changing the function _DEFAULT_SECOND_PARSER_.
I've changed the replace from `([^/?#]+?)` to `([^/?#]+)`

**Comment by GianlucaGuarini** [comment]
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.
