### ISSUE TITLE
history state is changed even when route is not found

### ISSUE THREAD

**Issue by osamutake** [riot/route#121]
I found that ``function go(path, title, shouldReplace)`` modifies browser's history, location and title before it checks if the specified route can be found by the parser.

https://github.com/riot/route/blob/c0e05d811f8448868a46e41db55a26f6bb8d7d2b/index.js#L191-L200

I'm afraid this is a wrong behavior.

``function click(e)`` does not ``preventDefault()`` when the route is not found, in order to allow browser to follow the link without intervention by the library.

https://github.com/riot/route/blob/c0e05d811f8448868a46e41db55a26f6bb8d7d2b/index.js#L167-L176

However, at this point, the history, title and location of the browser is already modified by the ``function go``, which interfere the default action of the browser.

I imagine ``function go`` should not modify browser's history, location and title when the route is not found:

```javascript
function go(path, title, shouldReplace) {
  // Server-side usage: directly execute handlers for the path
  if (!hist) return central[TRIGGER]('emit', getPathFromBase(path))
  
  routeFound = false
  emit()
  
  if(routeFound) {
    path = base + normalize(path)
    title = title || doc.title
    // browsers ignores the second parameter `title`
    shouldReplace
      ? hist.replaceState(null, title, path)
      : hist.pushState(null, title, path)
    // so we need to set it manually
    doc.title = title
  }
  return routeFound
}
```

**Comment by GianlucaGuarini** [comment]
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.
