### ISSUE TITLE
[Enhancement] subRoute.exec()

### ISSUE THREAD

**Issue by cybervaldez** [riot/route#124]
The problem with route.exec() is how it executes every defined router so it's pretty inefficient when I just want to execute my custom tag's subrouter upon mounting for the first time. Although I can use route.query() to check unfortunately i need to parse my path as well.

Here's my pattern
```
<app>
  <div data-is="{component}"></div>
</app>
```

**app.tag:**
```
route('search..', ()=> { 
this.component = 'search'; 
this.update() 
})
```

**search.tag:**
```
this.on("mount", ()=>{
  subRoute('search/*', (term)=>{ doSearch(term); }); 
  route.exec(); // this executes all other routers as well
});
```

**Comment by GianlucaGuarini** [comment]
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.
