### ISSUE TITLE
Browser location bar doesn't reflect the change of a route.push('/mynewroute') 

### ISSUE THREAD

**Issue by infuzz** [riot/route#129]
1. Describe your issue:
using `route.push('/mynewroute')` change the effective route state but doesn't affect location bar.

If I add `history.pushState({}, null, '/newroute')` the location bar chnage and reflects teh new route

2. Can you reproduce the issue?
https://plnkr.co/edit/mzPkS7SFt2eS2wkyqK67

3. On which browser/OS does the issue appear?
Windows 10/ chrome 77, but I guess it's on all platform

4. Which version of Riot/route does it affect?
4.0.0-beta.1

5. How would you tag this issue?

  - [ ] Question
  - [X] Bug
  - [ ] Discussion
  - [ ] Feature request
  - [ ] Tip
  - [ ] Enhancement
  - [ ] Performance

**Comment by GianlucaGuarini** [comment]
Fixed in 4.0.0-beta.2
