### ISSUE TITLE
Riot v4 Support Status 

### ISSUE THREAD

**Issue by hairlesshobo** [riot/route#130]
I have a new project that I am working on and would love to implement it with Riot v4, but I need routing support in order to do so. Was just wondering what the estimated time frame is for this project to be updated to support v4?

Thank you in advance!

**Comment by GianlucaGuarini** [comment]
@hairlesshobo thanks for your question. The new router is available here https://github.com/riot/route/tree/dev in beta release. It will be released soon

**Comment by hairlesshobo** [comment]
Wow, talk about a quick response!! Thank you, I look forward to checking it out!

**Comment by GianlucaGuarini** [comment]
The new Route.js just got released
