### ISSUE TITLE
Route does not work well with @riotjs/ssr

### ISSUE THREAD

**Issue by cybervaldez** [riot/route#135]
This shows up in the render
```
<route path="/about">
   <p>I should not show up in SSR</p>
</route>
```

While this is yielding an error
```
<route path="/browse/:month">
   <p>2. { route.params[0] }</p>
</route>
```
The best solution I can come up with is to pass an ssr : true attribute to my render

```
app.riot
    <route path="/about" if="{!state.ssr}">
      <p>About I should not show up....</p>
    </route>

    <route path="/browse/:month" if={!state.ssr}>
      <browse></browse>
    </route>

    <route path="/view/:month" if={!state.ssr}>
      <p>{route.params[0]}</p>
    </route>
```
I'm still trying to find a way to make my SSR truly isomorphic:
```
        let html = render('app', App, { 
            url : "/browse/february" // simulate browser url
        });
```

**Comment by GianlucaGuarini** [comment]
Have you tried something like:
```js
import { router } from '@riotjs/route'
export default {
  onBeforeMount(props) {
    if (props.initialRoute) {
      router.push(props.initialRoute)
    }
  }
}

```

**Comment by cybervaldez** [comment]
I'm unable to import it directly in the component.

`import { router } from '@riotjs/route';`
yields **ReferenceError: window is not defined**

To make routing work i'm registering the component globally in my bundle
```
import { register } from 'riot'
import { Route, Router } from '@riotjs/route'

// now the Router and Route components are globally available
register('router', Router)
register('route', Route)
```

so perhaps there's a way to access those global components from within a component?

**Comment by GianlucaGuarini** [comment]
Please check the https://github.com/riot/examples/tree/gh-pages/ssr example. I have added async SSR to the whole RIot.js echosystem
