### ISSUE TITLE
When trying to put a component inside a route it is not mounted.

### ISSUE THREAD

**Issue by drorhilman** [riot/route#139]
First, thank you very much for this amazing set of libraries! 

I have loaded, imported and registered several riot 4 pre-compiled tags into the view...   
One of them is a 'router_tag' that looks like this 
```HTML
<router_tag>
           <route path="/#learn">
                      <datasets_tag></datasets_tag>
           </route>
           <route path="/#apply">
                         APPLY
            </route>
</router_tag>
```
The `<router_tag>` is warped inside a parent with `<router>` tag and navigation links.
The links **work fine** when a pure HTML is inserted to the `<route>` tags (like in the 'APPLY'  example).

However - the content of the `<datasets_tag>` is not shown! (This tag is **not mounted**.) 
How can I force the mounting of the datasets_tag, when the user route to path='/#learn'?

**Comment by GianlucaGuarini** [comment]
@drorhilman could you please make a live demo of the issue?

**Comment by drorhilman** [comment]
I found it hard to get it to work outside my local machine.
the riot code is auto-generated by my program and may have some mistakes. I can't found them though.
Here's a plunkr link with the code I am trying to get working ...
https://embed.plnkr.co/OidEuMcddB5ab5f8VFQs/

**Comment by GianlucaGuarini** [comment]
@drorhilman the problem was in your code I have fixed it https://plnkr.co/edit/WkiuKRKYeDHs1f2rqhtr?p=preview

I don't see any route issue here but thanks for submitting your issue

**Comment by drorhilman** [comment]
Can't it be done with a server-side compiling? 
I see that you switch to the browser compiler mode.
