### ISSUE TITLE
Import route / router fails on Edge after rollup bundler

### ISSUE THREAD

**Issue by infuzz** [riot/route#140]
Hello, I got a strange issue when importing route and router only on Microsoft Edge 44.18362.449.0
I use rollup to import, compile with rollup-riot-plugin and make a bundle.js
rollup-riot-plugin : 2.6.0
riot : 4.8.9
route : 5.2.1

All was working well on chrome, firefox and Edge before using riot/route

I started to implement riot/route and now all is working only on chrome and firefox.
On edge page stays blank since there is critical error at starting:

What I got on console is this:
> SCRIPT1028: SCRIPT1028: Expected identifier, string or number

If I click on index.js (bundle) to see stack trace, seems that Edge stop on ...EachBinding in the create function.

function create(node, { evaluate, condition, itemName, indexName, getKey, template }) {
  const placeholder = document.createTextNode('');
  const parent = node.parentNode;
  const root = node.cloneNode();

  parent.insertBefore(placeholder, node);
  removeNode(node);

  return {
    ...EachBinding,  <------------------------------------- IE stops here ????
    childrenMap: new Map(),
    node,
    root,
    condition,
    evaluate,
    isTemplateTag: isTemplate(root),
    template: template.createDOM(node),
    getKey,
    indexName,
    itemName,
    placeholder
  }
}

Do you have any idea on what is happening ?

**Comment by GianlucaGuarini** [comment]
Thank you for submitting this issue I will investigate it asap

**Comment by GianlucaGuarini** [comment]
Are you compiling your code with babel js? I that case you should transpile with rollup also `@riotjs/dom-bindings`

**Comment by infuzz** [comment]
No,  I do not use Babel. Below is my rollup conf:
`import riot from 'rollup-plugin-riot'
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'
import copy from 'rollup-plugin-copy'
import css from 'rollup-plugin-css-only'
import json from 'rollup-plugin-json'

const production = !process.env.ROLLUP_WATCH;

export default {
    input: 'src/main.js',
    output: {
        file: 'www/index.js',
        format: 'esm',
        sourcemap:true
    },
	watch: {
		include: ['src/**','../../common/app/**','../../common/formr/**']
	},
    plugins: [
		riot(),
		nodeResolve(),// prise en charge des modules depuis node_modules
		commonjs(),
		json(), 
		css({ output: 'www/css/index.css' }),
        copy({
            targets: [
                {
                    src: 'src/index.html',
                    dest: 'www/'
                },
				{
                    src: 'src/assets/*',
                    dest: 'www/'
                },
				{
					src: 'node_modules/@fortawesome/fontawesome-pro/webfonts/*.woff2',
                    dest: 'www/webfonts/'
                },
				{/* for ios... */
					src: 'node_modules/@fortawesome/fontawesome-pro/webfonts/*.ttf',
                    dest: 'www/webfonts/'
                }
            ]
        })
    ]
}
`

**Comment by GianlucaGuarini** [comment]
Fixed in @riojts/route@5.2.2. Please remember to update your Riot.js version as well
