### ISSUE TITLE
Infinite loop when child is directly nested in route

### ISSUE THREAD

**Issue by markgarrigan** [riot/route#142]
When a child component is directly nested inside a route and calls a method from the parent component and the method calls update on the parent it creates an infinite loop.

https://next.plnkr.co/plunk/s4nvpkotEbQg1rAL

This is a workaround

https://next.plnkr.co/plunk/DX2B0DaUm0A1TafF

**Comment by GianlucaGuarini** [comment]
Fixed in v5.3.0 please check https://next.plnkr.co/edit/ojc8AqGADk47qUHb
