### ISSUE TITLE
Exclude path from routing

### ISSUE THREAD

**Issue by fri-sch** [riot/route#144]
I have an app that uses the router to render multiple pages like `/page1`, `/page2`, etc. On one of these pages I want to put links to external files like `/data/file1.txt`, etc.

Is there some way to exclude these links from being handled by the router?
Or can I somehow limit the router to handle only the page links?

I see that there is a `base` attribute, but I want to keep my app at the root level, so I can't use it to exclude the file links.

Thanks for your help!

**Comment by GianlucaGuarini** [comment]
Have you tried adding the [download attribute to your links](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement/download) `<a href="data/file.txt" download>Download file</a>`?

**Comment by fri-sch** [comment]
> Have you tried adding the [download attribute to your links](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement/download) `<a href="data/file.txt" download>Download file</a>`?

No, I haven't. But it works!
Thanks a lot for the hint! I wanted to use the `download` attribute anyway to assign a proper name for the downloaded file.
