### ISSUE TITLE
Route function rather than Update

### ISSUE THREAD

**Issue by BrockAtkinson** [riot/route#146]
Hi, I've been using riot for a number of years now, and have recently moved onto the new router (fantastic job btw). I find myself missing the previous `route()` handler [as mentioned in the v3 docs](https://github.com/riot/route/tree/v3/doc) and shown below:

```
<first-tag>
  <p>First tag</p>
  <script>
    route('/fruit/*', function(name) {
      /* do something common */
    })
  </script>
</first-tag>
```

When I tried replicating this functionality using the update lifecycle event, I ended up causing myself an infinite loop which caused my browser to exceed its max call stack, every time.

What I really want is a function that is only fired when the URL changes, like this package used to have, so I don't need to rely on the update function. If this exists and I'm missing something, please point it out.

**Comment by GianlucaGuarini** [comment]
Have you already tried something like?
```js
import { route } from '@riotjs/route'

route('/fruit/(.*)').on.value(({params}) => {
   const [name] = params
})
```

The new Riot.js router is completely built on the top of [rawth](https://github.com/gianlucaguarini/rawth)
