### ISSUE TITLE
How to catch "404 Not Found" routes properly? 

### ISSUE THREAD

**Issue by anonimusprogramus** [riot/route#147]
I have this routes block:

```javascript
<router>
  <route path="/">
    <home></home>
  </route>
  <route path="/about">
    About page
  </route>
  <route path="/faq">
    FAQ page
  </route>
  <route path="(.*)">
    404!
  </route>
</router>
```

When I browse `/about`, it says **About page 404!**

How to catch and show **404!** content only upon unregitered routes?

Thank you!

**Comment by GianlucaGuarini** [comment]
At moment I didn't create a `<switch>` route component yet but you could check how I have implemented the not found site here https://github.com/riot/examples/blob/gh-pages/ssr/app/app.riot

**Comment by anonimusprogramus** [comment]
Ah I see, was afraid I missed it in documentation. That ssr example gives me idea.

Btw, labeled enhancement, should this be closed or left opened?
 
Thank you.

**Comment by GianlucaGuarini** [comment]
@anonimusprogramus I take it as reminder for a `<switch>` component that is already on my TODO list
