### ISSUE TITLE
Add standalone route release

### ISSUE THREAD

**Issue by GianlucaGuarini** [riot/route#15]
Currently the `dist` folder contains `route.js` that is meant to be used in nodejs but actually there is no way to use a standalone release that could be directly included in a browser environment without riot or an additional build step.  Probably the package.json should point to the `lib/index.js` file and the `dist/route.js` should contain a build release including `riot-observable` as well.

**Comment by cognitom** [comment]
Let me see...

- AMD: it's ok
- global: need to load `riot-observable` before `riot-route`
- browserify / webpack: we can use `lib/index.js`

So, it seems that we don't have to provide it as UMD. My proposal would be...

- AMD package without `riot-observable`
- Stand alone package with `riot-observable` (use global)
- Naked `lib/index.js`

How about?

**Comment by GianlucaGuarini** [comment]
Yes it looks better to me. Otherwise anyone wants to use this module without riot needs to build it first

**Comment by cognitom** [comment]
@GianlucaGuarini ok, done!
Could you have a look at #16?

**Comment by GianlucaGuarini** [comment]
it got fixed, I have also fixed other small issues enabling the `use strict` mode

**Comment by cognitom** [comment]
Thanks for your fix ;)
