### ISSUE TITLE
Disable setting history.

### ISSUE THREAD

**Issue by RedKenrok** [riot/route#151]
Hello,

The router works perfectly, expect that is does a bit more than I would like it to. It automatically updates the windows history for me. Is there any way for me to disable this functionality or circumvent it.

Thank you in advance!

PS: I noticed that in the source code the function to get the history object from the window is mispelled as 'getHistorty'.

**Comment by GianlucaGuarini** [comment]
@RedKenrok thank you for your feedback. 

> Is there any way for me to disable this functionality or circumvent it.

no it's not possible nor I think to accept any patch to disable it

> expect that is does a bit more than I would like it to.

that's exactly your problem :) and you should solve outside of @riot/route. You should identify you application flaw and fix it, if @riot/route doesn't feed your needs try to use something else.

**Comment by RedKenrok** [comment]
Yeah. I'll look into setting up my own little router then. Thanks for the advice. In regards to the type, I have created a pull request.

**Comment by RedKenrok** [comment]
For others who stumble across this. I wrote 'riouter' an alternative router with accompanying riot components. See https://github.com/RedKenrok/node-riouter or https://www.npmjs.com/package/riouter for more information.
