### ISSUE TITLE
Download a file

### ISSUE THREAD

**Issue by markgarrigan** [riot/route#162]
How can I create a link inside a route that downloads a file?

I want to do...

`<a href="/path/to/some/file.pdf">PDF</a>`

But the router is handling it.

In a sort of related request... it would be really great if I could add something like a `data-no-router` attribute to any link I'd like the router to ignore.

**Comment by GianlucaGuarini** [comment]
Use the `download` attribute of the links https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a?retiredLocale=it#attr-download

**Comment by markgarrigan** [comment]
Thanks! For reference on anyone landing here my link looks like this now...

`<a href="relative/path/to/file.pdf" download="file.pdf">PDF</a>`
