### ISSUE TITLE
Default base path

### ISSUE THREAD

**Issue by gdub22** [riot/route#17]
I've found this doesn't work out of the box without setting `riot.route.base('/')`
Since this now uses `history.pushState` shouldn't the default base be `'/'` instead of `'#'`?

**Comment by cognitom** [comment]
Hi @gdub22, the default base is set to '#' because the compatibility to 2.2 or less.

The test has passed so I think it's OK. Are you pointing other things?
https://github.com/riot/route/blob/master/test/specs/core.specs.js#L25

**Comment by gdub22** [comment]
Ok, makes sense for compatibility.  It's not a bug, just a convenience for those who don't want to use hash urls.
