### ISSUE TITLE
Partial server-side support

### ISSUE THREAD

**Issue by gdub22** [riot/route#18]
We should simply allow something like the `exec` method to work server-side. This way, you can pass it the request path and let your route handlers do any rendering they normally would do on the client side.

I can work on a PR if you agree with the idea.

**Comment by cognitom** [comment]
Sounds great! PR is welcome. Thanks :-)

**Comment by gdub22** [comment]
https://github.com/riot/route/pull/19

**Comment by cognitom** [comment]
Now @gdub22 's works have been merged with #43 and #45 on riot-route#2.3.13! Thank you so much.
