### ISSUE TITLE
Wildcard filter does not match paths containing a dash

### ISSUE THREAD

**Issue by gdub22** [riot/route#20]
```js
route('fruit/*', function() {
  // This is not invoked
})
route('fruit/red-apple')
```
Failing test: https://github.com/gdub22/route/commit/0a1c43664460a6e304680d06e5ecd11fbd3a94d3

**Comment by cognitom** [comment]
Currently wildcards just match `\w`.
https://github.com/riot/route/tree/master/doc#routefilter-callback

Sometimes I'd like to use it like this:

 ```javascript
route('date/*-*/*/', function(year, month, day) {})
route('date/2015-09/25/')
```

Actually, at the first I tried to implement wildcard as `[^\/]+`, but I realised that it would not match this case:

 ```javascript
route('somepath?foo=*&bar=*', function(foo, bar) {})
route('somepath?foo=apple&bar=orange')
```

**Comment by cognitom** [comment]
@gdub22 you could change the default behaviour:
https://github.com/riot/route/tree/master/doc#second-parser

**Comment by gdub22** [comment]
Thanks, I can customize the parser.  I think letting the whole wildcard through may be a better default.

**Comment by cognitom** [comment]
@gdub22 another option could be `.+?`. Is this better?

**Comment by gdub22** [comment]
@cognitom thanks! `.+?` worked for me.  

The api to override that was a bit awkward, since I had to essentially duplicate the whole default second parser.  Many people aren't good at RegExp, that's why I suggest letting the whole path through, then they can use more comfortable parsing like String.split, etc. and power users can continue to use RegExp if they want.

**Comment by cognitom** [comment]
@gdub22 I've change the behaviour. `\w+` --> `[^/?#]+?`
https://github.com/riot/route/commit/4a0a9f2c026ff4ae3cc4e02b209babb78221291c

After some thoughts, I realised that `.+?` is not enough. Because sometimes

```
```

**Comment by cognitom** [comment]
Hi @gdub22, I've change the behaviour. `\w+` --> `[^/?#]+?`
https://github.com/riot/route/commit/4a0a9f2c026ff4ae3cc4e02b209babb78221291c

After some thoughts, I realised that `.+?` isn't enough. With `.+?`, the later example below will match to `fruit/apple?some_query` but it's not intuitive. So `[^/?#]+?`.

```
route('fruit/*', function(fruit) {})
route('fruit/apple')
route('fruit/apple?some_query') // user expects `apple` will match
```
