### ISSUE TITLE
Is change routing in routing callback supported?

### ISSUE THREAD

**Issue by txchen** [riot/route#22]
Hi, my scenario is like this:

* When there is no path in the url, I want to change the url to some default path

My code is now like this (v2.3):
```
studyRoute(view, id) {
    switch(view) {
    case 'news':
      require('./views/news-view.html')
      self.loadView('news-view', id)
      break
    default:
      riot.route('news/1')     // is this supported?
    }
  }
  riot.route(self.studyRoute)
  riot.route.start()
  riot.route.exec()
```

If I start with empty path url, it will bring me to `/#news/1`, which is correct. However after changing the url, the studyRoute is not called again, thus my actual logic is not executed.

I am not sure if it is due to I am not writing the correct code, or a bug. Please advise :)

**Comment by txchen** [comment]
I am also curious, if I want to achieve my goal, how should I change the code? Thanks!

**Comment by cognitom** [comment]
Hi @txchen, good question!
v2.3 has introduced [filter](http://riotjs.com/api/route/#riot-route-filter-callback). So now we can write down like this:

```js
function showNews(id) {
  if (!id) id = 1
  require('./views/news-view.html')
  loadView('news-view', id)
}

riot.route('/', showNews)
riot.route('/news/*', showNews)
riot.route.start()
riot.route.exec()
```

If you use this in the tag, it would be better to use [sub-router](http://riotjs.com/api/route/#riot-route-create):

```js
var subRoute = riot.route.create()
subRoute('/', showNews)
subRoute('/news/*', showNews)
```

See more [why we use sub-router](http://riotjs.com/api/route/#routing-priority), FYI.

**Comment by txchen** [comment]
@cognitom Thanks! But I am afraid this is not what I want.
My requirement is: is no path, then change the path to some default value. (/#news/1 for example)
Your code seems not changing the route. Or I missed some points?

**Comment by txchen** [comment]
FYI, actually I am trying to change my code to use riot 2.3, the existing one is: https://github.com/txchen/riot-hn/blob/gh-pages/src/app.html

It is now working well with 2.2.4. Now I want to make it using latest riot and router :)

**Comment by cognitom** [comment]
I see, you mean redirecting to another path.
You could use `riot.route('news/1')`, I think. Doesn't work fine?

**Comment by txchen** [comment]
Yes, it changes the url. However, the callback function is not executed after url is changed, thus, the actual mounting logic does not happen.
That's why I asked: is changing route supported inside routing callback logic?

**Comment by cognitom** [comment]
Yeah, should be. I'll check it soon, after lunch. Wait a few hours.

**Comment by txchen** [comment]
Thanks a lot! @cognitom 

I think you can take a look at https://github.com/txchen/riot-hn/blob/gh-pages/src/app.html
I'd like to make it continue to work in 2.3

**Comment by cognitom** [comment]
@txchen I'm still working on it. It seems the behaviour of `history.pushState`. I'll look into more deeply.

**Comment by cognitom** [comment]
Done! I've found the reason, finally.
`observable` doesn't allow `trigger()` on the same callback. To avoid this, I've added the stack in [emit function](https://github.com/riot/route/pull/23/files#diff-6d186b954a58d5bb740f73d84fe39073L81). But a bit awkward.
Could you have a look at this? #23 @txchen @GianlucaGuarini 
Thanks.

**Comment by txchen** [comment]
Yeah, a little bit awkward :)
I realized that I can workaround my issue by explicitly call my actual functional logic:
```
studyRoute(view, id) {
    switch(view) {
    case 'news':
      require('./views/news-view.html')
      self.loadView('news-view', id)
      break
    default:
      riot.route('news/1')
      self.loadView('news-view', 1)  // because I know here changing url will not trigger callback.
    }
  }
```

Not sure if this worth a fix to increase lib size, maybe my usage is not that common. You guys can decide.

**Comment by cognitom** [comment]
Ok, merged to master.
You could remove that line, after v2.3.1 ;-)

Thank you for your continuous contribution!
