### ISSUE TITLE
What would you change...?

### ISSUE THREAD

**Issue by Sendoushi** [riot/route#27]
Hi guys,

New to riot and redux and trying to follow better practices and patterns.
So, I've done this example:
https://github.com/Sendoushi/code-examples/blob/redux-riot/src/bootstrap.js

How would you improve?
I know this isn't an issue, a help wanted.

**Comment by GianlucaGuarini** [comment]
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.
