### ISSUE TITLE
riot.route not working in ie for 2.3.1

### ISSUE THREAD

**Issue by TimWillis** [riot/route#28]
I have this setup for riot routing -

var router = function(page,id) {
function change_page(current_page){
RiotControl.trigger('page_changed', current_page, xmenu.last_page)
xmenu.last_page = current_page;
}
page = !page ? 'home' : page;
change_page(page);
}
// Riot router
riot.route(router)
// Execute router function once for rendering the items
riot.route.exec(router);

when I click a link with href="#home" or set location.hash the callback function 'router' is never called in ie11 works fine in chrome and ff.

**Comment by cognitom** [comment]
@TimWillis it looks a bug. I'm fixing another issue on the example below maybe related.
https://github.com/riot/examples/tree/gh-pages/router-page-switcher
Wait a little. Thanks.

**Comment by nippur72** [comment]
I'm stuck on the same issue :cry:

**Comment by jpikl** [comment]
I can confirm this issue on IE 11 and Edge. The cause seems to be the 'popstate' event (used for URL change detection) which is not correctly implemented in IE/Edge (see https://connect.microsoft.com/IE/Feedback/Details/1528993).

I'm currently using the following workaround:

    window.addEventListener('hashchange', function() {
        riot.route.exec();
    });

**Comment by duongphuhiep** [comment]
I'm stuck too!  the router works in Chrome + Firefox but NOT work in IE 11 and IE Edge
Here the plnkr samples (using the latest 2.3.11), 

http://plnkr.co/edit/YZpDmc?p=preview

**Comment by GianlucaGuarini** [comment]
I am working on this issue...soon I will make a pull request
