### ISSUE TITLE
regression Bug of the router API?

### ISSUE THREAD

**Issue by duongphuhiep** [riot/route#30]
https://github.com/riot/riot/issues/1385

```
    /**
     * Disable the default riot route parser
     */
    riot.route.parser(function(path) {
	console.info("parser",path);
        return path; // return the path "as-is"
    });

    /**
     * Handle route change event
     */
    riot.route(function (path) {
        console.info("route is change to",path);
    });

    riot.route.start(true);
```

I expect that my callback is called on every change of the url (as in the version 2.3.4)

But it is not true in case the route is changed from `index.html#blog`  to `index.html#`
The callback in the `route.parser` is invoked with empty path, and the `riot.route` callback is not called

PS: I don't know how to generate route problem with plunker

**Comment by cognitom** [comment]
@duongphuhiep does it help you?
http://riotjs.com/examples/plunker/?app=router-page-switcher

**Comment by duongphuhiep** [comment]
thanks, here the problem

http://plnkr.co/edit/6nGkr5wDYZ5gKX3pMdA4?p=preview

**Comment by cognitom** [comment]
@duongphuhiep thanks.

This line causes the issue. From v2.3.11, if the parser returns falsy value, the execution will skipped. This was introduced for fixing #25 
https://github.com/riot/route/blob/v2.3.11/lib/index.js#L183

I think we could change it to this:
```js
if (typeof args == 'undefined') {
```

It may fix your issue. I'll make a PR and test later.

FYI, a temporary fix could be like this on your Plunker:
```js
riot.route.parser(function(path) {
  console.info("parser",path);
  return '/' + path; // return the path "as-is" with a slash
});
```
