### ISSUE TITLE
click back button on browser doesn't go back to the last state?

### ISSUE THREAD

**Issue by cloudship** [riot/route#31]
Hi guys, with the riot-router, when I click the back button on the browser, the page address did change back to the previous one but the page was not reloaded. Is this a bug or designed like this? if expected, how should I make the content also change back? Regards!

**Comment by cloudship** [comment]
to be more exact, I'm asking why the [[riot.route 'filter', callback]] fails to detect the URI when it was changed back?

**Comment by cloudship** [comment]
oh, I found out that the router was not started. Problem solved when I manually started it.

But even when it was not started, [[riot.route TO, title]] can still work...

**Comment by cognitom** [comment]
:smile: 
@cloudship `riot.route.start()` just starts to listen the events. So basically, the methods work without `riot.route.start()`.
