### ISSUE TITLE
Browser-inconsistencies in router.start() and router.exec()

### ISSUE THREAD

**Issue by chmanie** [riot/route#33]
When calling `riot.route.start()` in Safari it gets auto-executed immediately. When I pass `true` to this function my handler for the route is executed twice. This is only the case for Safari and not for FF or Chrome.

See this plunker:

http://plnkr.co/edit/uzjtYKZ9Rc5qb2T0XGaY?p=preview

Open it in Chrome and see the console:

```
initializing
route accessed
```

Safari:

```
initializing
route accessed
route accessed
```

**Comment by GianlucaGuarini** [comment]
@cognitom Any chance to fix this bug for the next riot release? Should I fix it?  Let me know if you need any help

**Comment by cognitom** [comment]
@GianlucaGuarini thanks a lot!
