### ISSUE TITLE
Make routes crawlable

### ISSUE THREAD

**Issue by kfreiman** [riot/route#4]
Is it posible to make hash fragment starts with `#!`? 
It is necessary for Search Engine Crawlers.
https://developers.google.com/webmasters/ajax-crawling/docs/specification

**Comment by cognitom** [comment]
I'm not sure because we're still discussing about it.
Personally I'd like to add `router.base()` api. Then we could set the base URL (`string` or `RegExp`)

```javascript
router.base(/^.*#/) // default
router.base(/^.*#!/) // hashbang
router.base('/') // without hash
```

**Comment by kfreiman** [comment]
`router.base` would be great!

**Comment by cognitom** [comment]
FYI, the final syntax:

```javascript
router.base('#') // default
router.base('#!') // hashbang
router.base('/') // without hash
router.base('/app') // under app directory
```

**Comment by kfreiman** [comment]
Thanks!

**Comment by tipiirai** [comment]
Nice!
