### ISSUE TITLE
Mapping routes to tags

### ISSUE THREAD

**Issue by syropian** [riot/route#41]
Does anyone have a best practice or nice way to show/hide tags on a per-route basis? Ideally it would be mounting/unmounting the tag from the DOM entirely over simply showing/hiding, but I'm interested to see what others are doing.

**Comment by cognitom** [comment]
@syropian this was my try, and I have a plan to rebuild this on the `riot-route`.
https://github.com/cognitom/ikki#html-router

I'm guessing that it'll be practical when the `if` implementation of Riot is fixed.

**Comment by Infeligo** [comment]
Here is [my gist](https://gist.github.com/Infeligo/b1edc269ab3d8ce5e412) with a simplistic show/hide, where route is mapped onto element by ID.

**Comment by cognitom** [comment]
Recently I've started making [another helper library](https://github.com/cognitom/riot-action). With this, mapping [could be easier](https://github.com/cognitom/riot-action/blob/master/demo/src/main.js) :-)

```js
import { util } from 'riot-action'
util.mount('#container', [
  { route: 'notepad/*', tag: 'app-notepad' },
  { route: 'history',   tag: 'app-history' }
])
```

**Comment by avimar** [comment]
I did it like so: https://gist.github.com/avimar/2020226327810f2e49b4

**Comment by GianlucaGuarini** [comment]
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.
