### ISSUE TITLE
Isomorphic examples

### ISSUE THREAD

**Issue by rstacruz** [riot/route#46]
I see that the docs mention riot-route is capable of isomorphic operation.

Is it possible to run two routers at once?

**Comment by GianlucaGuarini** [comment]
> Is it possible to run two routers at once?

It is possible to run two routers at same time https://github.com/riot/route/tree/master/doc#routecreate, and in the next release our router will work on the server as well https://github.com/riot/route/pull/45

**Comment by rstacruz** [comment]
Ah, nice, I saw that route.create documentation and assumed it was only for when using it with `riot`. I'm using riot-route with another stack.

Can I do this?

```js
router = riot.route.create()
router('/users', () => ...)
router('/user/:id', (id) => ...)
router('/users')
```

How can I promote `router` as the main router?

**Comment by rstacruz** [comment]
...ahh, I see, all routers will be active and will listen to the document's events. would be cool to be able to make a decoupled router like so:


```js
router = riot.route.create()
router('/users', () => ...)
router('/user/:id', (id) => ...)

router('/users') // navigate to /users only on this router
router.start()   // listen to document changes
router.stop()    // stop listening
```

**Comment by GianlucaGuarini** [comment]
> ...ahh, I see, all routers will be active and will listen to the document's events. would be cool to be able to make a decoupled router...

@rstacruz In theory you can use only subrouters to achieve this [more info](http://riotjs.com/api/route/#subroute-stop):
```js
// start listening the window hashchange/popstate events
riot.route.start()
// create your main router as subrouter
var router = riot.route.create()
router('users/:id', () => ...)
// do your stuff
router.stop() // kill the old routes and its listeners
// create a new subroute promoting this new instance as main router
router = riot.route.create()
router('users', () => ...)
// do your stuff
router.stop() // and so on..
```

**Comment by GianlucaGuarini** [comment]
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.
