### ISSUE TITLE
Should be able to replace current route without history entry

### ISSUE THREAD

**Issue by Infeligo** [riot/route#47]
[History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API) provides two methods for updating state: `pushState` and `replaceState`. The latter is used when there is no intention to create a new history entry. There are realistic use cases for this. Other frameworks that have routing provide such method (e.g. [Backbone](http://backbonejs.org/#Router-navigate) and [Mithril](http://lhorie.github.io/mithril/mithril.route.html#redirecting)). Is it possible to add such option to Riot?

**Comment by cognitom** [comment]
I'm implementing this feature on `dev` branch:

```js
shouldReplace
  ? hist.replaceState(null, title, path)
  : hist.pushState(null, title, path)
```

Usage:

```js
var replaceFlag = true
route('path/to', 'Page Title', replaceFlag)
```

But, I couldn't make a test for it, because PhantomJS (1.9) doesn't support `history.back()`...
Is there any good idea?

**Comment by cognitom** [comment]
@GianlucaGuarini any idea about testing this? I've been trying to move to PhantomJS 2.0, but there're other difficulties...
[Protractor](https://angular.github.io/protractor/) could be another option?

**Comment by GianlucaGuarini** [comment]
@cognitom you can run the tests using our browserstack account

**Comment by cognitom** [comment]
Oh, thanks. I've almost forgot about that. I'll have a try ;)

**Comment by cognitom** [comment]
@Infeligo we can use this feature from `riot-route@2.3.15` or `riot@2.3.13` :-)
