### ISSUE TITLE
route & route.base functions allow regex

### ISSUE THREAD

**Issue by ifraixedes** [riot/route#50]
I'm starting to create an app for one client using Riot and one of the use cases is that the base route can change due localization, so I tried to use a regular expression in `riot.route.base` method and it worked as a charm even though the docs don't mention it.

I've been inspecting the code to see if that's expected or not, because I wanted to make sure that it won't stop to work in path/minor version and [I've clearly seen that method comments (api docs) specify that the parameters can be a `string` or `RegExp`](https://github.com/riot/route/blob/v2.3.15/lib/index.js#L261), so I make the assumption that's a feature.

If you can assert all of this, I will send a PR with an update of the docs.

**Comment by ifraixedes** [comment]
I was wrong yesterday when I said that everything worked as charm.

Working more on that app, I don't get the result that I expect and I would like to know if I misunderstand something or it may be a bug.

My examples is the next:

My base route of the can be `http://localhost/shop/es` or `http://localhost/shop/ca`; on any case it serves the same riot application without any change.

I set the base path with `riot.route.base('/shop/es')` and I get one problem which is that if I do `riot.route('/product')` then the browser URL is `http://localhost/shop/esproduct` while I would expect that it was `http://localhost/shop/es/product`; this is not a big deal and I could manage it replacing with the history API appending the `/` at the end when the page load.

My bigger issue is that I want to use regular expressions to handle the the 2 options `/es` and `/ca` so I thought that to do `riot.route.base(/.*(es|ca)$/)`  because in production `/shop` doesn't exist; the root URL works OK but if I execute `riot.route('/product');` then the browser URL looks like `http://localhost/.*(es%7Cca)$/product`.

To remove complexity to the case, I've tried to do `riot.route.base(/shop\/(es|ca)$/)` but then I've got `http://localhost/shop//(es%7Cca)$/product` 

and if I do `riot.route.base(/\/shop\/(es|ca)$/)` then I get a browser exception

```
riot.js:327 Uncaught SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'http://shop//(es%7Cca)$/product' cannot be created in a document with origin 'http://localhost' and URL 'http://localhost/shop/es
```

**Comment by GianlucaGuarini** [comment]
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.
