### ISSUE TITLE
subRoute.stop() doesn't work (stop is undefined)

### ISSUE THREAD

**Issue by wiz** [riot/route#51]
I need to load and unload sub-components dynamically and they have inner routes themselves.
I wanted to stop subRoute when component is unmounting, so the handlers wouldn't accumulate.

The code from router API doesn't work. I've tried in in playground and the error is same.
``` js
var subRoute = riot.route.create()
subRoute('/fruit/apple', function() { /* */ })
subRoute.stop()
```

**Comment by wiz** [comment]
Patch for a missing test:

``` diff
diff --git a/test/specs/server.specs.js b/test/specs/server.specs.js
index 6a7c77e..3ab29a5 100644
--- a/test/specs/server.specs.js
+++ b/test/specs/server.specs.js
@@ -34,7 +34,12 @@ describe('Server-side specs', function() {
     it('can create sub route context', function() {
       expect(route.create).to.not.throwException()
     })
-    
+
+    it('can terminate sub route context', function() {
+      var subRoute = route.create()
+      expect(subRoute.stop).to.not.throwException()
+    })
+
     it('can define route handlers', function() {
       expect(route).withArgs(function(){}).to.not.throwException()
       expect(route).withArgs('/fruit', function(){}).to.not.throwException()
```

**Comment by chmanie** [comment]
Is there a workaround? This is a very important feature!

**Comment by wiz** [comment]
I've used `riot.route.stop.bind(subRoute)` to some success.

**Comment by chmanie** [comment]
> I've used riot.route.stop.bind(subRoute) to some success.
:+1: 

Preparing a PR.

**Comment by wiz** [comment]
I'm conceding now that subrouting is FUBAR :weary:

Perhaps apps should stick to central routing and trigger custom signals to achieve multi-dispatch behaviour.
