### ISSUE TITLE
Version bump / dev branch

### ISSUE THREAD

**Issue by gdub22** [riot/route#54]
Could `riot/route` get a patch version bump and be updated in the next riot release?
There are a couple bug fixes that would be nice to include along with riot.
Also, the dev branch needs to be merged into master.

**Comment by GianlucaGuarini** [comment]
@gdub22 of course @cognitom will you have time for this task? Otherwise I will try to do it asap, the next riot release will definitely contain the new route

**Comment by cognitom** [comment]
@GianlucaGuarini sorry, I'm a bit busy during this month...
Could you do that this time? It helps me so much. Thanks.

**Comment by GianlucaGuarini** [comment]
no prob @cognitom ;)
