### ISSUE TITLE
Route match action should receive parsed segments

### ISSUE THREAD

**Issue by lukeed** [riot/route#58]
There's very little point in having a route matcher that does not (1) regard the values obtained by `riot.parser.fn1` and (2) inconsistently produces callback function parameters.

Eg:

``` js
riot.route('/fruit/*', function(name) { /* */ })
riot.route('/fruit/apple', function() { /* */ })
riot.route('/fruit/orange', function() { /* */ })
```

Not only is there a `name` parameter JUST for wildcard matching, but this setup requires `fruit` as the bare minimum abstraction.

Expectedly, all route callbacks should plug into the values obtained by `parser.fn1`. In the default scenario, this looks like:

``` js
riot.route('/fruit/*', function(collection, id, action) { /* */ })
riot.route('/fruit/apple', function(collection, id, action){ /* */ })
riot.route('/fruit/orange', function(collection, id, action) { /* */ })
```

Of course, some parameters may still be undefined, but at least you can always expect a set of parameters in the callback.

My second point: We have to have a full set of routes just for `fruit`, and will have to repeat the same set for `cars` and another for `trees`, etc.

This practice only makes sense when you're designating routes for a specific tag or a specific set of tags. This same practice prevent you from having a succinct, global level routes declaration.

The same solution allows for:

``` js
// (1)
riot.route('..', function (collection, id, action) {
  // ..
});

// (2)
riot.route('fruit/apple/..', function (custom, parser, args) {
  // .. long-tail url, read it
});
```

`(1)`: While this isn't a recommended **only** solution, it allows for a nice last resort/"catch-all" which has the power to run its own logic based on params

`(2)`: Dependent on our desired URL structure (and appropriate parser fn), we can allow for deep, complex URLs and handle them all at once without having to declare multiple blocks, repeating boilerplate.

Anyway, Issue getting a bit long here. If this is approved, I have the matching PR ready to be opened. It's a simple 2-line fix

**Comment by GianlucaGuarini** [comment]
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.
