### ISSUE TITLE
href="{ window.history.back() }" on Riot Tag anchor element

### ISSUE THREAD

**Issue by karlpatrickespiritu** [riot/route#62]
Every time the tag is mounted, the page automatically redirects back to the last url when using the back functionality in js.

``` javascript
<a href="{ window.history.back() }" class="button secondary expanded raised-button ink">Back</a>
```

**Comment by karlpatrickespiritu** [comment]
gives me this header when mounting.

![untitled](https://cloud.githubusercontent.com/assets/10472504/16484775/a81732e0-3eed-11e6-8060-b1db85d5d3ec.png)

**Comment by cognitom** [comment]
`history.back()` returns nothing.
https://developer.mozilla.org/en-US/docs/Web/API/History

I guess you may want to do that like this?

```javascript
<a href="#" onclick={ click }>Back</a>
<script>
click (e) {
  history.back()
}
</script>
```
