### ISSUE TITLE
Routing priority broken

### ISSUE THREAD

**Issue by gdub22** [riot/route#63]
Previously, when a match is found, no other routes are triggered. Now multiple routes are firing.

I noticed this updating from riot 2.3.18 -> 2.5.0.
It appears to be caused by changes in riot observable, because it works correctly if I roll that back. Nothing in this route repo has changed in a while.

---

Example:
```js
route('/post/*.amp.html', function() { /* */ })
route('/post/*', function() { /* */ })
```

Given the url: `/post/title-of-my-post`
The expected result is for the second route to trigger.
The actual result is both get triggered, and also appears to be a race condition of which one gets triggered first.

**Comment by GianlucaGuarini** [comment]
@cognitom could you please have a look?

**Comment by GianlucaGuarini** [comment]
Ah I guess it's the events namespacing the problem. I think we need either to remove the namespaced events or simply normalize them inside the router

**Comment by cognitom** [comment]
@GianlucaGuarini thanks!
Ah, "name spaced" and "namespacing", finally understood what happened 😲

**Comment by GianlucaGuarini** [comment]
@cognitom oups my typo 😄

**Comment by artstar** [comment]
So good feature was removed:(
Is there any plans to add event namespacing back?

**Comment by GianlucaGuarini** [comment]
@artstar no we are removing the fat from riot and events namespacing was causing performance issues and other several issues in the router. If you want to use this feature i guess you can do it with probably 10 lines of code in a mixin. Let me know if you need help
