### ISSUE TITLE
Issue with relative links

### ISSUE THREAD

**Issue by pavel** [riot/route#64]
### Description

Relative links work only on second click, if the `location.hash` is set.

### To reproduce

1. Open a demo: http://output.jsbin.com/jafikuquwe#test/11.
2. Click on "Google.com" link (first click, sends you straight to the `www.google.com`)
3. Go back to the demo.
4. Click on "Test.html" (first click does no visual effect, location.hash changes)
5. Click on "Test.html" again. (now you're sent to the test.html page)

---
Edit link: http://jsbin.com/jafikuquwe/edit?html,js,output

**Comment by GianlucaGuarini** [comment]
@cognitom could you please check this issue?

**Comment by cognitom** [comment]
@pavel thank you for your reporting. It will be fixed on next release 😄

**Comment by pavel** [comment]
@cognitom You're welcome. Keep up the good work!
