### ISSUE TITLE
Open in new window/tab?

### ISSUE THREAD

**Issue by avimar** [riot/route#67]
I'm used to link with a CTRL+click opening in a new tab/window. Is there a way to do that with the `riot.route`?
Or replace my `riot.route` with a `href` that the router picks up?

Thanks!

**Comment by cognitom** [comment]
Hi @avimar, `riot-route` doesn't intercept `click` events if `ctrl` key is pushed.
https://github.com/riot/route/blob/v2.4.0/lib/index.js#L141

So it should work as normal.
