### ISSUE TITLE
Introduces WebdriverIO

### ISSUE THREAD

**Issue by cognitom** [riot/route#68]
For testing this library, I'd like to introduce [WebdriverIO](http://webdriver.io/). We're using Karma now, but even if it's a simple unit test, it can't handle page transition. It makes the tests difficult, especially for the libraries like `riot-route`.

I've done the most part of [the research](https://github.com/cognitom/webdriverio-examples/tree/master/wdio-wo-local-selenium). But some points are still open. Your feedback is welcome.
- [x] WebdriveIO research (ver4 is awsome, actually)
- [x] makes Java free environment locally
- [x] creates [phantomjs lanucher](https://github.com/cognitom/wdio-phantomjs-service) for WebdriveIO
- [ ] how to measure the coverage
- [ ] how to live together with Karma tests

[Saucelabs widget](https://wiki.saucelabs.com/display/DOCS/Using+Status+Badges+and+the+Browser+Matrix+Widget+to+Monitor+Test+Results) doesn't support multiple test in one repo, IFIK...

**Comment by GianlucaGuarini** [comment]
@cognitom could you make a pull request? I would like to see how it behaves. Have you also checked http://nightwatchjs.org/?

**Comment by cognitom** [comment]
Sure! Maybe next weekend..

I tried some frameworks:

- Nightwatch
- WebdriverIO
- Codecept
- Nightmare 
- Chimp

Nightwatch was actually my first option. These all has pros and cons. I like these features of WebdriverIO:

- not tightly coupled with assertion libraries
- all methods are sync with wdio (they use [fibers](https://github.com/laverdet/node-fibers) to convert async to sync)

**Comment by GianlucaGuarini** [comment]
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.
