### ISSUE TITLE
Routing bug after `riot.route('some/path')`

### ISSUE THREAD

**Issue by moritzschepp** [riot/route#70]
I discovered strange behavior that I believe can't be right. I'm seeing this on
- windows 7
- IE 11.0.9600.18449
- riotjs 2.6.2
- riot-route 2.5.0

Have a look at the plunkr here and click the links one after the other:
https://plnkr.co/edit/bGUkr1sueLDtcFrxd9sj

The problem is that the last click actually does change the url but no events are triggered (hashchange, popstate), also the riot handler is not run as in the steps before.

Also, I noticed that step 3 doesn't seem to add state. Perhaps this is why IE thinks that the current fragment is already "#a/b" so there is no event to trigger?

Any ideas?

**Comment by sota1235** [comment]
I have a same bug, but I have no idea... 😭

**Comment by cognitom** [comment]
Oh, sorry.
Will check this issue again, asap.

**Comment by GianlucaGuarini** [comment]
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.
