### ISSUE TITLE
Is there a CDN release of this

### ISSUE THREAD

**Issue by zaun** [riot/route#71]
I'm playing around with the 3.0 version of Riot and the router has been removed. I'm wondering if there is a release of the stand alone router on a CDN someplace?

I've checked a few including cdn.jsdelivr.net (where I'm grabbing the 3.0 riot from) but I cant seem to locate the router code.

I'm using `https://cdn.rawgit.com/riot/route/master/dist/route.js` for now, but a released version on CDN would be much better.

**Comment by cognitom** [comment]
@zaun no, at this point. But that's a good point! We should provide a CDN version. Will do, asap 😉

**Comment by cognitom** [comment]
@zaun sorry to be late. At last I've send the PR to jsdelivr. I hope they'll merge it soon 😄 
https://github.com/jsdelivr/jsdelivr/pull/14883

**Comment by cognitom** [comment]
Successfully merged. I'm waiting their bot crawl our library.
https://github.com/jsdelivr/jsdelivr/tree/master/files/riot-route

**Comment by cognitom** [comment]
Done.
https://www.jsdelivr.com/?query=riot-route
