### ISSUE TITLE
Unable to include lib/index.js in the new riot 2.3.0 build

### ISSUE THREAD

**Issue by GianlucaGuarini** [riot/route#8]
I have tried including the new router in the new riot build `https://github.com/riot/riot/blob/2.3.0/lib/riot.js` but it does not pass the old router tests. Do I need to test a build script with esperanto or do we stick with smash? In case we want to use smash the router code should be wrapped in its own IIFE avoiding to pollute the global scope. What do you recommend?

**Comment by cognitom** [comment]
@GianlucaGuarini I've just [update the repo](https://github.com/riot/router/commit/6a6a14378ae527a7669d50e6bff75a3265c02a7e). Now we have two `dist` files. You could import later one. How about?

- `dist/router.js` : UMD for general purpose
- `dist/riot.router.js`: Specialized for Riot.js

We need more discussion to move ES6 (esperanto), I think.

**Comment by cognitom** [comment]
Oops, I've fixed some issue.
https://github.com/riot/router/commit/3c2862bab3f113fa58069dd650e34e9821b9923f

**Comment by cognitom** [comment]
Could you have a look at this?
https://github.com/riot/riot/pull/1151

**Comment by GianlucaGuarini** [comment]
thanks I will check it asap
