### ISSUE TITLE
route(from, to)

### ISSUE THREAD

**Issue by Shyam-Chen** [riot/route#82]
```js
route('/en', '/en/home');
```
```js
route('/zh', '/zh/home');
```

**Comment by cognitom** [comment]
@Shyam-Chen is this a feature request for *redirection*?
Unfortunately, the API `route(string, string)` is already used for [this](http://riotjs.com/api/route/#routeto-title-shouldreplace).

At this point, I'd like to close this issue. Feel free to reopen it. Pls describe more about what you think, then.
