### ISSUE TITLE
route.query() not working as expected when using # base

### ISSUE THREAD

**Issue by simonomis** [riot/route#83]
When using # as the base, `route.query()` for these URLs is not behaving correctly:

- `index.html?param=xyz#/search` => `{ param: "xyz#/search" }`
- `index.html?param=xyz#/search?q=keyword` => `{ param: "xyz#/search?q=keyword" }`

Where `?param=xyz` are query params for the server rather than the router.

It's not entirely clear how it should behave. The docs don't address it and the specs only test with '/' base. My expectation is that if using a # base, the router should only consider query params after the #. Which would look like this:

- `index.html?param=xyz#/search` => `{}`
- `index.html?param=xyz#/search?q=keyword` => `{ q: "keyword" }`

When using '/' as the base, the issue doesn't exist because there's only one set of query params which is shared between server and router.

I didn't manage to write a spec to show this failing because the code behaves differently when running in the test suite (it doesn't use location.href).

**Comment by cognitom** [comment]
@simonomis right. Thank you for pointing it out.
Your spec seems reasonable for me.

**Comment by GianlucaGuarini** [comment]
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.
