### ISSUE TITLE
How to retrieve the matching filter on route?

### ISSUE THREAD

**Issue by fujiyama-pl** [riot/route#85]
Is it possible to read original filter in riot.route or somewhere else for current page?
For example if I route to '/fruit/sth' how can I retrieve '/fruit/*' as defined matching pattern during route/mount.

**Comment by cognitom** [comment]
Hi @fujiyama-pl, you can modify [our built-in parser](https://github.com/riot/route/blob/v3.1.0/src/index.js#L47-L62). 

It might be like below. I've just added `.concat(filter)` to the returning value:

```javascript
function yourCustomParser (path, filter) {
  const f = filter
    .replace(/\?/g, '\\?')
    .replace(/\*/g, '([^/?#]+?)')
    .replace(/\.\./, '.*')
  const re = new RegExp(`^${f}$`)
  const args = path.match(re)

  if (args) return args.slice(1).concat(filter)
}
route.parser(null, yourOriginalParser)
```

See [Second Parser section](http://riotjs.com/api/route/#second-parser) on our document.
