### ISSUE TITLE
scroll to top on route change

### ISSUE THREAD

**Issue by continuata** [riot/route#88]
How should we handle scrolling to the top of a page on route change?
Scroll position is maintained across routing between pages, which is unexpected.

**Comment by ogatakex** [comment]
```
let subRoute = route.create();
subRoute((...args) => {
    window.scroll(0, 0);
});
```

**Comment by GianlucaGuarini** [comment]
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.
