### ISSUE TITLE
Riot Router wildcard * not working

### ISSUE THREAD

**Issue by Miss-Git** [riot/route#91]
Hello
I am testing a simple code:

`  route('/test/*', function (tst) {
        console.log(tst);
    });`

When I route to **mydomain/test/sth**

It gives so many irrelevant errors. Seems like it has problem with  " * ".

What should I do?

TNX

------------------------------------------------------------------------------------------------
P.S 1:
The problem is with more than one level URL in route not the star wildcard

**Comment by GianlucaGuarini** [comment]
sorry provide a live example we could test, your issue description is not enough.
