### ISSUE TITLE
How can I let the browser follow the link?

### ISSUE THREAD

**Issue by AndreasHeintze** [riot/route#93]
If route(function() {}) callback is triggered, but I still want to let the browser follow the link, how can I do that?

**Comment by GianlucaGuarini** [comment]
what do you mean by let the browser follow the link?

**Comment by AndreasHeintze** [comment]
To just load the page the link is pointing to.

**Comment by GianlucaGuarini** [comment]
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.
