### ISSUE TITLE
Force a route feature.

### ISSUE THREAD

**Issue by ghstahl** [riot/route#96]
I notice that we have an emit(force) in the code, and when I set it to true in the console it does what I need it to do.
Can we get something that from a usage point of view looks like this.

var force = true
riot.route(route,null,null, force);

I have a need where there is a handler for the route, but that handler's job is to dynamically build the real routes on demand.

1. Initial route /Hello..  catch everything, and based on a config rebuild it to the following;
2. handler does a route.stop and rebuilds it to something like this.
route(/Hello/*,()=>{})
route(/Hello,()=>{})

incoming /Hello/Dog which is handled by /Hello..
new route gets created  /Hello/*, and then the original route is reissued  route(original);  // need to force this one.

Thanks

**Comment by cognitom** [comment]
Hi @ghstahl, doesn't [route.exec()](https://github.com/riot/route/tree/master/doc#routeexec) work in your situation?
It sounds a little bit tricky to build routes dynamically for me. Isn't it possible to create all of them before loading?

**Comment by ghstahl** [comment]
https://github.com/ghstahl/riotjs-bootstrap3-startkit-sidebar
I actually dump the entire route and then event out via riotcontrol to all the route-contributors to repopulate.  So in reality it is simply doing the same load that I did at startup.  I am dynamically bringing in a mini riotjs app that has its own routes, so those routes are not known up front.  Currently to get by I do a route("") followed by a route(original).. complete hack until you can get me a force.

**Comment by ghstahl** [comment]
Thank you.
route.exec() works for me.

on a side note:
Can I get you to add an getter to fetch the current route the same way you have one for query;
route.query = function() {}
ie.
route.current = function() {}

**Comment by GianlucaGuarini** [comment]
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.
