### ISSUE TITLE
Router has Problems in Cordova-App

### ISSUE THREAD

**Issue by marcel-se-best** [riot/route#97]
In Cordova-Apps the router has problems with links as absoluterelative pathes like "/homepage/...".

Please change the RE_ORIGIN-RegEx in index.js:12 from 
`/^.+?\/\/+[^\/]+/ `
to 
`/^.+?\/\/([^\/]+|)/`

The following patterns are then valid an the router works in webapps and Cordova-Apps as well:
- http://host:80/home
- http://host:80/home/someMore
- file:///home
- file:///home/someMore
- etc.

Best regards,
Marcel

**Comment by GianlucaGuarini** [comment]
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.
